const express = require('express');
const app = express();
const bodyParser = require('body-parser');
const PORT = process.env.PORT || 3000;

// database
const db = require('./models');

// bodyparser middleware
app.use(bodyParser.urlencoded({extended: true}));
app.use(bodyParser.json());

// serve static assets
app.use(express.static(__dirname + '/public'));

// test pets
// _id is hardcoded as a string, since _id will be auto-generated by mongoDB
const pets = [
  {
    _id: '',
    name: 'string',
    type: 'string',
    age: int,
    bio: 'string',
    image: 'string',
    liked: []
  },
  {
    _id: '',
    name: 'string',
    type: 'string',
    age: int,
    bio: 'string',
    image: 'string',
    liked: []
  },
  {
    _id: '',
    name: 'string',
    type: 'string',
    age: int,
    bio: 'string',
    image: 'string',
    liked: []
  },
  {
    _id: '',
    name: 'string',
    type: 'string',
    age: int,
    bio: 'string',
    image: 'string',
    liked: []
  }
];

// test matches
const matches = [

];

// test chat history
const chats = [

];

// root route
app.get('/', (req, res) => {
  res.sendFile('views/index.html', {root: __dirname});
});

//

// start server
app.listen(PORT, () => console.log(`Server running on ${PORT}`));